Stocktaking/Controllers/DisplacementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class DisplacementController : Controller
    {
        private ApplicationContext database;

        public DisplacementController(ApplicationContext context)
        {
            database = context;
        }


        public async Task<IActionResult> Displacements()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var displacements = database.Displacements.Where(r => r.OrganizationId == user.OrganizationId).OrderByDescending(r => r.When).ToList();

            var model = new List<DisplacementWithItems>();
            foreach(var displacement in displacements)
            {
                var itemsId = database.ItemDisplacement.Where(r => r.DisplacementId == displacement.Id).ToList();
                var itemsForModel = new List<Item>();
                var totalcost = 0.0;
                foreach (var itemId in itemsId)
                {
                    var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemId.ItemId);
                    totalcost += item.Cost;
                    itemsForModel.Add(item);

                }
                model.Add(new DisplacementWithItems { Items = itemsForModel, FromWhere = displacement.FromWhere, Status = displacement.Status, When = displacement.When, WhereTo = displacement.WhereTo, WhoAdd = displacement.WhoAdd, TotalCost = totalcost });
            }

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteItemsDisplacement()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var items = database.Items.Where(r => r.OrganizationId == user.OrganizationId && r.Status != "Списан").ToList();
            var model = new DeleteItemsViewModel();
            foreach (var item in items)
            {
                model.DeleteItems.Add(new DeleteItemViewModel { Id = item.Id, InventoryNumber = item.InventoryNumber, Name = item.Name, Status = item.Status });
            }
            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> DeleteItemsDisplacement(DeleteItemsViewModel model)
        {

            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var displacement = new Displacement { OrganizationId = user.OrganizationId, When = DateTime.Now, Status = "Списание", WhoAdd = user.FirstName + " " + user.LastName };
            database.Displacements.Add(displacement);
            await database.SaveChangesAsync();

            foreach (var itemSelect in model.DeleteItems)
            {
                if (itemSelect.Select)
                {
                    var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemSelect.Id);
                    item.Status = "Списан";
                    item.RoomId = 0;
                    item.UserId = 0;
                    database.Update(item);
                    await database.SaveChangesAsync();

                    var itemDisplacement = new ItemDisplacement { ItemId = item.Id, DisplacementId = displacement.Id };
                    database.ItemDisplacement.Add(itemDisplacement);
                    await database.SaveChangesAsync();
                }
            }

            return RedirectToAction("AllItems", "Item");



            

        }

        [HttpGet]
        public async Task<IActionResult> AddDisplacement()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var rooms = database.Rooms.Where(r => r.OrganizationId == user.OrganizationId).ToList();
            ViewBag.Rooms = new SelectList(rooms, "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDisplacement(AddDisplacementViewModel model)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var rooms = database.Rooms.Where(r => r.OrganizationId == user.OrganizationId).ToList();
            ViewBag.Rooms = new SelectList(rooms, "Name", "Name");
            if (ModelState.IsValid)
            {

                var displasement = new Displacement { FromWhere = model.FromWhere, WhereTo = model.WhereTo, Status = "Поступление", When = DateTime.Now, OrganizationId = user.OrganizationId, WhoAdd = user.FirstName + " " + user.LastName };
                database.Displacements.Add(displasement);
                await database.SaveChangesAsync();

                return RedirectToAction("AddItemsDisplacement", "Item", new { displacementId = displasement.Id, whereTo = model.WhereTo });

            }
            else ModelState.AddModelError("", "Некоректный ввод");

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MoveItemsDisplacement(int itemId)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemId);
            ViewBag.Rooms = database.Rooms.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.RoomId)).ToList();
             ViewBag.Allusers = database.Users.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.UserId )).ToList();
            var model = new MoveItemDisplacementViewModel { ItemId = itemId };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MoveItemsDisplacement(MoveItemDisplacementViewModel model)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var item = await database.Items.FirstOrDefaultAsync(r => r.Id == model.ItemId);
            ViewBag.Rooms = database.Rooms.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.RoomId)).ToList();
            ViewBag.Allusers = database.Users.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.UserId)).ToList();
            if (model.RoomId == 0 ^ model.UserId == 0)
            {
                var displacement = new Displacement { WhoAdd = user.FirstName + " " + user.LastName, OrganizationId = user.OrganizationId, When = DateTime.Now, Status = "Перемещение" };
                if(item.RoomId != 0)
                {
                    var room = await database.Rooms.FirstOrDefaultAsync(r => r.Id == item.RoomId);
                    displacement.FromWhere = room.Name;
                }
                else
                {
                    var userItem = await database.Users.FirstOrDefaultAsync(r => r.Id == item.UserId);
                    displacement.FromWhere = user.FirstName + " " + user.LastName;
                }


                if(model.RoomId != 0)
                {
                    var whereTo = await database.Rooms.FirstOrDefaultAsync(r => r.Id == model.RoomId);
                    displacement.WhereTo = whereTo.Name;
                    item.RoomId = model.RoomId;
                    item.UserId = 0;

                }
                else if (model.UserId != 0)
                {
                    var whereTo = await database.Users.FirstOrDefaultAsync(r => r.Id == model.UserId);
                    displacement.WhereTo = whereTo.FirstName + " " + whereTo.LastName;
                    item.UserId = model.UserId;
                    item.RoomId = 0;
                }

                database.Update(item);
                await database.SaveChangesAsync();

                database.Displacements.Add(displacement);
                await database.SaveChangesAsync();

                database.ItemDisplacement.Add(new ItemDisplacement { DisplacementId = displacement.Id, ItemId = item.Id });
                await database.SaveChangesAsync();

                return RedirectToAction("AllItems", "Item");
            }
            else ModelState.AddModelError("", "Некоректный ввод");

            return View(model);
        }
    }
}

Stocktaking/Controllers/InventoryReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class InventoryReportController : Controller
    {
        private readonly ApplicationContext database;

        public InventoryReportController(ApplicationContext context)
        {
            database = context;
        }

        [HttpGet]
        public async Task<IActionResult> AllInventoryReports()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);

            if (user == null) return NotFound();

            var inventoryReports = await database.InventoryReports.Where(r => r.OrganizationId == user.OrganizationId && r.EndInventory == true).ToListAsync();
            var model = new List<InventoryReportWithItemsViewModel>();

            foreach(var invReport in inventoryReports)
            {
                var invReportWithItems = new InventoryReportWithItemsViewModel(invReport);
                var items = await database.ItemsCheck.Where(r => r.InventoryReportId == invReport.Id).ToListAsync();
                invReportWithItems.Items = items;
                invReportWithItems.Cost = items.Where(r => r.Check == false).Sum(s => s.Cost);
                model.Add(invReportWithItems);
            }

            return View(model);
        }
    }
}

Stocktaking/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class UserController : Controller
    {
        private ApplicationContext database;

        public UserController(ApplicationContext context)
        {
            database = context;
        }

        [HttpGet]
        public async Task<IActionResult> AllUsers()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var users = database.Users.Where(r => r.OrganizationId == user.OrganizationId).ToList();
            var usersWithItemsModel = new List<UserWithItemsViewModels>();

            foreach(var oneuser in users)
            {
                var items = database.Items.Where(r => r.UserId == oneuser.Id && r.Status != "Списан").ToList();
                usersWithItemsModel.Add(new UserWithItemsViewModels { FirstName = oneuser.FirstName, LastName = oneuser.LastName, Position = oneuser.Position, Items = items });
            }
            return View(usersWithItemsModel);
        }
    }
}

Stocktaking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
    </head>
<body >
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Stocktaking</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form class="d-flex" asp-action="SearchItem" asp-controller="Item" method="post">
            <input class="form-control me-2" type="text" placeholder="..." aria-label="Search" name="searchstring">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
        </form>
       
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" asp-action="Logout" asp-controller="Account">Выйти</a>
            </li>
        </ul>
    </header>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse d-print-none">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                Главная
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Displacements" asp-controller="Displacement">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                                Перемещения
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="AllItems" asp-controller="Item">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                                Имущество
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="AllUsers" asp-controller="User">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                                Сотрудники
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-action="AllInventoryReports" asp-controller="InventoryReport">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                                Отчеты инветаризаций
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="EditUser" asp-controller="Account">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                                Редактирование профиля
                            </a>
                        </li>
                    </ul>

                   
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
               
                @RenderBody()

                <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="807" height="340" style="display: block; height: 272px; width: 646px;"></canvas>


            </main>
        </div>
    </div>
</body>
</html>