Stocktaking/Controllers/DisplacementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class DisplacementController : Controller
    {
        private ApplicationContext database;

        public DisplacementController(ApplicationContext context)
        {
            database = context;
        }


        public async Task<IActionResult> Displacements()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var displacements = database.Displacements.Where(r => r.OrganizationId == user.OrganizationId).OrderByDescending(r => r.When).ToList();

            var model = new List<DisplacementWithItems>();
            foreach(var displacement in displacements)
            {
                var itemsId = database.ItemDisplacement.Where(r => r.DisplacementId == displacement.Id).ToList();
                var itemsForModel = new List<Item>();
                var totalcost = 0.0;
                foreach (var itemId in itemsId)
                {
                    var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemId.ItemId);
                    totalcost += item.Cost;
                    itemsForModel.Add(item);

                }
                model.Add(new DisplacementWithItems { Items = itemsForModel, FromWhere = displacement.FromWhere, Status = displacement.Status, When = displacement.When, WhereTo = displacement.WhereTo, WhoAdd = displacement.WhoAdd, TotalCost = totalcost });
            }

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteItemsDisplacement()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var items = database.Items.Where(r => r.OrganizationId == user.OrganizationId && r.Status != "Списан").ToList();
            var model = new DeleteItemsViewModel();
            foreach (var item in items)
            {
                model.DeleteItems.Add(new DeleteItemViewModel { Id = item.Id, InventoryNumber = item.InventoryNumber, Name = item.Name, Status = item.Status });
            }
            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> DeleteItemsDisplacement(DeleteItemsViewModel model)
        {

            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var displacement = new Displacement { OrganizationId = user.OrganizationId, When = DateTime.Now, Status = "Списание", WhoAdd = user.FirstName + " " + user.LastName };
            database.Displacements.Add(displacement);
            await database.SaveChangesAsync();

            foreach (var itemSelect in model.DeleteItems)
            {
                if (itemSelect.Select)
                {
                    var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemSelect.Id);
                    item.Status = "Списан";
                    item.RoomId = 0;
                    item.UserId = 0;
                    database.Update(item);
                    await database.SaveChangesAsync();

                    var itemDisplacement = new ItemDisplacement { ItemId = item.Id, DisplacementId = displacement.Id };
                    database.ItemDisplacement.Add(itemDisplacement);
                    await database.SaveChangesAsync();
                }
            }

            return RedirectToAction("AllItems", "Item");



            

        }

        [HttpGet]
        public async Task<IActionResult> AddDisplacement()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var rooms = database.Rooms.Where(r => r.OrganizationId == user.OrganizationId).ToList();
            ViewBag.Rooms = new SelectList(rooms, "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDisplacement(AddDisplacementViewModel model)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var rooms = database.Rooms.Where(r => r.OrganizationId == user.OrganizationId).ToList();
            ViewBag.Rooms = new SelectList(rooms, "Name", "Name");
            if (ModelState.IsValid)
            {

                var displasement = new Displacement { FromWhere = model.FromWhere, WhereTo = model.WhereTo, Status = "Поступление", When = DateTime.Now, OrganizationId = user.OrganizationId, WhoAdd = user.FirstName + " " + user.LastName };
                database.Displacements.Add(displasement);
                await database.SaveChangesAsync();

                return RedirectToAction("AddItemsDisplacement", "Item", new { displacementId = displasement.Id, whereTo = model.WhereTo });

            }
            else ModelState.AddModelError("", "Некоректный ввод");

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MoveItemsDisplacement(int itemId)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemId);
            ViewBag.Rooms = database.Rooms.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.RoomId)).ToList();
             ViewBag.Allusers = database.Users.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.UserId )).ToList();
            var model = new MoveItemDisplacementViewModel { ItemId = itemId };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> MoveItemsDisplacement(MoveItemDisplacementViewModel model)
        {
            var user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var item = await database.Items.FirstOrDefaultAsync(r => r.Id == model.ItemId);
            ViewBag.Rooms = database.Rooms.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.RoomId)).ToList();
            ViewBag.Allusers = database.Users.Where(r => (r.OrganizationId == user.OrganizationId) && (r.Id != item.UserId)).ToList();
            if (model.RoomId == 0 ^ model.UserId == 0)
            {
                var displacement = new Displacement { WhoAdd = user.FirstName + " " + user.LastName, OrganizationId = user.OrganizationId, When = DateTime.Now, Status = "Перемещение" };
                if(item.RoomId != 0)
                {
                    var room = await database.Rooms.FirstOrDefaultAsync(r => r.Id == item.RoomId);
                    displacement.FromWhere = room.Name;
                }
                else
                {
                    var userItem = await database.Users.FirstOrDefaultAsync(r => r.Id == item.UserId);
                    displacement.FromWhere = user.FirstName + " " + user.LastName;
                }


                if(model.RoomId != 0)
                {
                    var whereTo = await database.Rooms.FirstOrDefaultAsync(r => r.Id == model.RoomId);
                    displacement.WhereTo = whereTo.Name;
                    item.RoomId = model.RoomId;
                    item.UserId = 0;

                }
                else if (model.UserId != 0)
                {
                    var whereTo = await database.Users.FirstOrDefaultAsync(r => r.Id == model.UserId);
                    displacement.WhereTo = whereTo.FirstName + " " + whereTo.LastName;
                    item.UserId = model.UserId;
                    item.RoomId = 0;
                }

                database.Update(item);
                await database.SaveChangesAsync();

                database.Displacements.Add(displacement);
                await database.SaveChangesAsync();

                database.ItemDisplacement.Add(new ItemDisplacement { DisplacementId = displacement.Id, ItemId = item.Id });
                await database.SaveChangesAsync();

                return RedirectToAction("AllItems", "Item");
            }
            else ModelState.AddModelError("", "Некоректный ввод");

            return View(model);
        }
    }
}

Stocktaking/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class ItemController : Controller
    {

        private ApplicationContext database;

        public ItemController(ApplicationContext context)
        {
            database = context;
        }




        [HttpGet]
        public async Task<IActionResult> AllItems()
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            if (user != null)
            {

                var items = database.Items.Where(r => r.OrganizationId == user.OrganizationId).OrderBy(r => r.Status).ToList();
                if (items != null)
                {
                    var itemsViewModels = new List<ItemInRoomViewModel>();
                    foreach (var item in items)
                    {
                        string name, roomName;
                        name = roomName = "";
                        if (item.RoomId != 0)
                        {
                            var room = await database.Rooms.FirstOrDefaultAsync(r => r.Id == item.RoomId);
                            roomName = room.Name;
                        };


                         if (item.UserId != 0)
                        {
                            var itemuser = await database.Users.FirstOrDefaultAsync(r => r.Id == item.UserId);
                            name = itemuser.FirstName + "  " + itemuser.LastName;
                        }

                        itemsViewModels.Add(new ItemInRoomViewModel { Name = item.Name, Description = item.Description, InventoryNumber = item.InventoryNumber, Status = item.Status, RoomName = roomName, Username = name, Id = item.Id, Cost = item.Cost });
                    }
                    return View(itemsViewModels);
                }


            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public async Task<IActionResult> AddItemsDisplacement(int displacementId, string whereTo)
        {
            var itemsId = database.ItemDisplacement.Where(r => r.DisplacementId == displacementId).ToList();
            var items = new List<Item>();
            foreach (var id in itemsId)
            {
                var item = await database.Items.FirstOrDefaultAsync(r => r.Id == id.ItemId);
                items.Add(item);
            }

            return View(new AddItemsDisplacementVIewModels { Items = items, DisplacementId = displacementId, WhereTo = whereTo });
        }

        [HttpGet]
        public async Task<IActionResult> AddItem(string displacementId, string WhereTo)
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
            var room = await database.Rooms.FirstOrDefaultAsync(r => r.Name == WhereTo);
            var model = new AddItemViewModel { DisplacementId = Int32.Parse(displacementId), RoomSelectId = room.Id };


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(AddItemViewModel model)
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);

            if (ModelState.IsValid)
            {
                var item = await database.Items.FirstOrDefaultAsync(r => r.InventoryNumber == model.InventoryNumber && r.OrganizationId == user.OrganizationId);
                if (item == null)
                {
                    item = new Item { Name = model.Name, Description = model.Description, InventoryNumber = model.InventoryNumber, OrganizationId = user.OrganizationId, Status = "Новый", RoomId = model.RoomSelectId, Cost = model.Cost };

                    database.Items.Add(item);
                    await database.SaveChangesAsync();

                    var itemDisplacement = new ItemDisplacement { ItemId = item.Id, DisplacementId = model.DisplacementId };
                    database.ItemDisplacement.Add(itemDisplacement);
                    await database.SaveChangesAsync();
                    var room = await database.Rooms.FirstOrDefaultAsync(r => r.Id == model.RoomSelectId);
                    return RedirectToAction("AddItemsDisplacement", "Item", new { displacementId = model.DisplacementId, whereTo = room.Name });

                }
                else ModelState.AddModelError("", "Инвентарный номер должен быть уникален");

            }
            else ModelState.AddModelError("", "Некоректный ввод");

            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> EditItem(int itemId)
        {
            if (!User.Identity.IsAuthenticated) return RedirectToAction("Login", "Account");
            var item = await database.Items.FirstOrDefaultAsync(r => r.Id == itemId);
            var model = new EditItemViewModel
            {
                Id = item.Id,
                InventoryNumber = item.InventoryNumber,
                Name = item.Name,
                Description = item.Description,
                Cost = item.Cost,
                Status = item.Status,
                OrganizationId = item.OrganizationId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditItem(EditItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (database.Items.Where(r => r.Id != model.Id).All(r => r.InventoryNumber != model.InventoryNumber && r.OrganizationId == model.OrganizationId))
                {
                    var item = await database.Items.FirstOrDefaultAsync(r => r.Id == model.Id);
                    item.InventoryNumber = model.InventoryNumber;
                    item.Name = model.Name;
                    item.Description = model.Description;
                    item.Cost = model.Cost;
                    item.Status = model.Status;
                    database.Update(item);
                    await database.SaveChangesAsync();
                    return RedirectToAction("AllItems");
                }
                else ModelState.AddModelError("", "Инвентарный номер должен быть уникален");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SearchItem(string searchstring)
        {
            if (searchstring != null)
            {
                User user = await database.Users.FirstOrDefaultAsync(r => r.Username == User.Identity.Name);
                ViewBag.Message = searchstring;
                var items = await database.Items.Where(r => ((EF.Functions.Like(r.Name.ToLower().Trim(' '), "%" + searchstring.ToLower() + "%", " ") || r.Name.ToLower().Trim(' ') == searchstring.ToLower().Trim(' ')) && r.OrganizationId == user.OrganizationId)).ToListAsync();
                return View(items);
            }
           
            return View();
        }
    }
}

Stocktaking/Controllers/QrController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QRCoder;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class QrController : Controller
    {
        private ApplicationContext database;

        public QrController(ApplicationContext context)
        {
            database = context;
        }

        [HttpGet]
        public async Task<IActionResult> QrCode(string inventoryNumber)
        {
            Item item = await database.Items.FirstOrDefaultAsync(r => r.InventoryNumber == inventoryNumber);
            return View(item);
        }
        [HttpGet]
        public IActionResult GetQRCode(string inventoryNumber)
        {
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(inventoryNumber, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);

            FileContentResult result;

            using (var memStream = new System.IO.MemoryStream())
            {
                qrCodeImage.Save(memStream, System.Drawing.Imaging.ImageFormat.Jpeg);
                result = this.File(memStream.GetBuffer(), "image/jpeg");
            }

            return result;
        }

        
    }
}

Stocktaking/Views/Item/AddItem.cshtml
@model AddItemViewModel
@{
    ViewData["Title"] = "Добавление предмета";
}

<h1 style="margin-left:4%; margin-top:20px;">Добавление нового предмета</h1>
<hr />
<div class="row" style="margin-left:5%;">
    <div class="col-md-4">
        <form method="post" asp-controller="Item" asp-action="AddItem">
            <div asp-validation-summary="All"></div>
            <div class="form-group">
                <label asp-for="Name"></label><br />
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label> <br />
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description"></span>
            </div>

            <div class="form-group">
                <label asp-for="InventoryNumber"></label> <br />
                <input asp-for="InventoryNumber" class="form-control" />
                <span asp-validation-for="InventoryNumber"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cost"></label> <br />
                <input asp-for="Cost" class="form-control" type="number" />
                <span asp-validation-for="Cost"></span>
            </div>



            <input type="hidden" asp-for="RoomSelectId" value="@Model.RoomSelectId" />
            <input type="hidden" asp-for="DisplacementId" value="@Model.DisplacementId" />
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-outline-success" />
            </div>

        </form>
    </div>
</div>

Stocktaking/Views/Item/AddItemsDisplacement.cshtml
@model AddItemsDisplacementVIewModels
@{
    ViewData["Title"] = "Добавление материальный ценностей";
}



<h1 style="margin-left:4%; margin-top:20px;">Добавление материальный ценностей</h1>
<hr />

@{
    var parms = new Dictionary<string, string>
    {
                { "displacementId", @Model.DisplacementId.ToString() },
                { "WhereTo", @Model.WhereTo }
            };
}
<a asp-action="AddItem" asp-controller="Item"asp-all-route-data="parms" class="btn btn-outline-success" style="margin-left:4%;">Добавить предмет</a>

<br />
<br />
<div class="row" style="margin-left:4%;">
    <div class="col-md-5">
        @foreach (var item in Model.Items)
        {
            <div class="alert alert-info mt-3">
                <b>Наименование предмета: </b> @item.Name<br />
                <b>Описание предмета: </b> @item.Description<br />

                
            </div>
            <br />

        }
    </div>



</div>

<div style="margin-left:4%;">
    @if (Model.Items.Capacity > 0)
    {
        <a asp-action="AllItems" asp-controller="Item" class="btn btn-outline-primary" style="margin-left:4%;">Завершить</a>
    }
</div>

Stocktaking/Views/Item/AllItems.cshtml
@model List<ItemInRoomViewModel>
@{
    ViewData["Title"] = "Все предметы";
}

<h1>Всё имущество предприятия</h1>

<a asp-action="AddDisplacement" asp-controller="Displacement" class="btn btn-outline-success">Добавить поступление</a>
 <a asp-action="DeleteItemsDisplacement" asp-controller="Displacement" class="btn btn-outline-danger">Добавить списание</a>

<table class="table">
    <tr><th>Наименование предмета</th><th>Инвентарный номер</th><th>Описание</th><th>Состояние предмета</th><th>Стоимость</th><th>Находится в</th><th>В личном пользовании</th><th></th><th></th><th></th></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.InventoryNumber</td>
            <td>@item.Description</td>
            <td>@item.Status</td>
            <td>@item.Cost</td>
            <td>@item.RoomName</td>
            <td>@item.Username</td>
            <td><a asp-action="EditItem" asp-controller="Item" asp-route-itemId="@item.Id" class="btn btn-outline-secondary">Изменить</a></td>
            <td><a asp-action="QrCode" asp-controller="Qr" asp-route-inventoryNumber="@item.InventoryNumber" class="btn btn-outline-info">Qr Code</a></td>
            <td>@if(item.Status != "Списан"){<a asp-action="MoveItemsDisplacement" asp-controller="Displacement" asp-route-itemId="@item.Id" class="btn btn-outline-warning">Переместить предмет</a>}</td>
        </tr>
    }
</table>

Stocktaking/Views/Item/EditItem.cshtml
@model EditItemViewModel
@{
    ViewData["Title"] = "Редактирование предмета";
}


<h1 style="margin-left:4%; margin-top:20px;">Редактирование предмета</h1>
<hr />
<div class="row" style="margin-left:5%;">
    <div class="col-md-4">
        <form method="post" asp-controller="Item" asp-action="EditItem">
            <div asp-validation-summary="All"></div>
            <div class="form-group">
                <label asp-for="Name"></label><br />
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label> <br />
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description"></span>
            </div>

            <div class="form-group">
                <label asp-for="InventoryNumber"></label> <br />
                <input asp-for="InventoryNumber" class="form-control" />
                <span asp-validation-for="InventoryNumber"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cost"></label> <br />
                <input asp-for="Cost" class="form-control" type="number" />
                <span asp-validation-for="Cost"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status"></label> <br />
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status"></span>
            </div>

            <input type="hidden" asp-for="Id" value="@Model.Id" />
            <input type="hidden" asp-for="OrganizationId" value="@Model.OrganizationId" />
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-outline-success" />
            </div>

        </form>
    </div>
</div>

Stocktaking/Views/Item/SearchItem.cshtml
@model List<Stocktaking.Data.Models.Item>
@{
    ViewData["Title"] = "Поиск";
}

<h1>Результат поиска по запросу @ViewBag.Message</h1>

@if (@Model != null)
{
    @foreach (var item in Model)
    {
        <div class="alert alert-light mt-3">
            <b>Наименование: </b> @item.Name<br />
            <b>Описание:</b> @item.Description <br />
            <b>Инветарный номер: </b> @item.InventoryNumber <br />
            <b>Состояние: </b> @item.Status <br />
            <b>Стоимость: </b> @item.Cost <br />

        </div>
        <br />
    }
}
else
{
    <div>
        <label>Ничего не найдено.</label>
    </div>

}