Stocktaking/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stocktaking.Data;
using Stocktaking.Data.Models;
using Stocktaking.Data.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stocktaking.Controllers
{
    public class OrganizationController : Controller
    {
        private ApplicationContext database;

        public OrganizationController(ApplicationContext context)
        {
            database = context;
        }

        [HttpGet]
        public IActionResult Organizations()
        {

            List<Organization> organizations = database.Organizations.ToList();

            return View(organizations);
        }

        [HttpGet]
        public IActionResult AddOrganization() => View();

        [HttpPost]
        public async Task<IActionResult> AddOrganization(AddOrganiztionViewModels model)
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == model.Username);
            var organization = new Organization { Name = model.Name };

            database.Organizations.Add(organization);
            await database.SaveChangesAsync();

            if(user != null)
            {
                user.OrganizationId = organization.Id;
                user.Role = "admin";
                database.Update(user);
                await database.SaveChangesAsync();
            }
            

            return RedirectToAction("AllRooms","Room");
        }

        [HttpPost]
        public async Task<IActionResult> ChoiceOrganizations(string username, int organizationId)
        {
            User user = await database.Users.FirstOrDefaultAsync(r => r.Username == username);
            if (user != null)
            {
                user.OrganizationId = organizationId;
                user.Role = "user";
                database.Update(user);
                await database.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Stocktaking/Views/Organization/AddOrganization.cshtml
@model AddOrganiztionViewModels 
@{
    ViewData["Title"] = "AddOrganization";
}

<h1>Добавление организации</h1>

<br />

<form method="post" asp-action="AddOrganization" asp-controller="Organization">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <input type="hidden" asp-for="Username" value="@User.Identity.Name" /> <br />

    <input type="submit" value="Добавить" class="btn btn-outline-primary" /> 
</form>

Stocktaking/Views/Organization/Organizations.cshtml
@model List<Stocktaking.Data.Models.Organization>
@{
    ViewData["Title"] = "Организации";
}
@{
    Layout = null;
}
<head>
    <link href="~/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" type="text/css" rel="stylesheet" />

</head>

<h1 style="margin-left:4%; margin-top:20px;">Все организации</h1>
<hr />

<a asp-action="AddOrganization" asp-controller="Organization" class="btn btn-outline-success" style="margin-left:4%;">Добавить организацию</a>

<br />
<br />
<div class="row" style="margin-left:4%;">
    <div class="col-md-5">
        @foreach (var organization in Model)
        {
            <div class="alert alert-warning mt-3">
                <b>Наименование организации: </b> @organization.Name<br />
                <form method="post" asp-action="ChoiceOrganizations" asp-controller="Organization">
                    <input type="hidden" value="@User.Identity.Name" name="username" />
                    <input type="hidden" value=" @organization.Id" name="organizationId" />
                    <input type="submit" class="btn btn-outline-info" value="Выбрать" />
                </form>

            </div>
            <br />
        }
    </div>
</div>